//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Text.MainWindow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class FontsToRead : global::System.Configuration.ApplicationSettingsBase {
        
        private static FontsToRead defaultInstance = ((FontsToRead)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new FontsToRead())));
        
        public static FontsToRead Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заголовок")]
        public string T0 {
            get {
                return ((string)(this["T0"]));
            }
            set {
                this["T0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Верхняя_панель")]
        public string T1 {
            get {
                return ((string)(this["T1"]));
            }
            set {
                this["T1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средняя_правая_панель")]
        public string T2 {
            get {
                return ((string)(this["T2"]));
            }
            set {
                this["T2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Средняя_левая_панель")]
        public string T3 {
            get {
                return ((string)(this["T3"]));
            }
            set {
                this["T3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Нижняя_панель")]
        public string T4 {
            get {
                return ((string)(this["T4"]));
            }
            set {
                this["T4"] = value;
            }
        }
    }
}
