//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Text.MainWindow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class TopText : global::System.Configuration.ApplicationSettingsBase {
        
        private static TopText defaultInstance = ((TopText)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TopText())));
        
        public static TopText Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LCtrl+1\r\nАтрибуты файлов")]
        public string Text1 {
            get {
                return ((string)(this["Text1"]));
            }
            set {
                this["Text1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LCtrl+2\r\nДиск")]
        public string Text2 {
            get {
                return ((string)(this["Text2"]));
            }
            set {
                this["Text2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Text3 {
            get {
                return ((string)(this["Text3"]));
            }
            set {
                this["Text3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Text4 {
            get {
                return ((string)(this["Text4"]));
            }
            set {
                this["Text4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Text5 {
            get {
                return ((string)(this["Text5"]));
            }
            set {
                this["Text5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RCtrl+1\r\nАтрибуты файлов")]
        public string Text6 {
            get {
                return ((string)(this["Text6"]));
            }
            set {
                this["Text6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RCtrl+2\r\nДиск")]
        public string Text7 {
            get {
                return ((string)(this["Text7"]));
            }
            set {
                this["Text7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Text8 {
            get {
                return ((string)(this["Text8"]));
            }
            set {
                this["Text8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Text9 {
            get {
                return ((string)(this["Text9"]));
            }
            set {
                this["Text9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Text0 {
            get {
                return ((string)(this["Text0"]));
            }
            set {
                this["Text0"] = value;
            }
        }
    }
}
