//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Colors {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class AdditionalWindowColors : global::System.Configuration.ApplicationSettingsBase {
        
        private static AdditionalWindowColors defaultInstance = ((AdditionalWindowColors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AdditionalWindowColors())));
        
        public static AdditionalWindowColors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C3C3C")]
        public string Фон {
            get {
                return ((string)(this["Фон"]));
            }
            set {
                this["Фон"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Заголовок {
            get {
                return ((string)(this["Заголовок"]));
            }
            set {
                this["Заголовок"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Текст {
            get {
                return ((string)(this["Текст"]));
            }
            set {
                this["Текст"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string Фон_текста {
            get {
                return ((string)(this["Фон_текста"]));
            }
            set {
                this["Фон_текста"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public string Фон_кнопки {
            get {
                return ((string)(this["Фон_кнопки"]));
            }
            set {
                this["Фон_кнопки"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Текст_кнопки {
            get {
                return ((string)(this["Текст_кнопки"]));
            }
            set {
                this["Текст_кнопки"] = value;
            }
        }
    }
}
