//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Colors {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class MainWindowColors : global::System.Configuration.ApplicationSettingsBase {
        
        private static MainWindowColors defaultInstance = ((MainWindowColors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MainWindowColors())));
        
        public static MainWindowColors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C3C3C")]
        public string Фон {
            get {
                return ((string)(this["Фон"]));
            }
            set {
                this["Фон"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Текст {
            get {
                return ((string)(this["Текст"]));
            }
            set {
                this["Текст"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string Нажатые_клавиши {
            get {
                return ((string)(this["Нажатые_клавиши"]));
            }
            set {
                this["Нажатые_клавиши"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Ненажатые_клавиши {
            get {
                return ((string)(this["Ненажатые_клавиши"]));
            }
            set {
                this["Ненажатые_клавиши"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C3C3C")]
        public string Фон_левого_окна {
            get {
                return ((string)(this["Фон_левого_окна"]));
            }
            set {
                this["Фон_левого_окна"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C3C3C")]
        public string Фон_правого_окна {
            get {
                return ((string)(this["Фон_правого_окна"]));
            }
            set {
                this["Фон_правого_окна"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Текст_правого_окна {
            get {
                return ((string)(this["Текст_правого_окна"]));
            }
            set {
                this["Текст_правого_окна"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Тескт_левого_окна {
            get {
                return ((string)(this["Тескт_левого_окна"]));
            }
            set {
                this["Тескт_левого_окна"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF8C8C8C")]
        public string Фон_выделенного_элемента {
            get {
                return ((string)(this["Фон_выделенного_элемента"]));
            }
            set {
                this["Фон_выделенного_элемента"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF3C3C3C")]
        public string Граница_выделенного_элемента {
            get {
                return ((string)(this["Граница_выделенного_элемента"]));
            }
            set {
                this["Граница_выделенного_элемента"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#60CDCDCD")]
        public string Фон_слайдера {
            get {
                return ((string)(this["Фон_слайдера"]));
            }
            set {
                this["Фон_слайдера"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#60CDCDCD")]
        public string Ползунок_сдайдера {
            get {
                return ((string)(this["Ползунок_сдайдера"]));
            }
            set {
                this["Ползунок_сдайдера"] = value;
            }
        }
    }
}
