//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Colors {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class SettingsWindowColors : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsWindowColors defaultInstance = ((SettingsWindowColors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsWindowColors())));
        
        public static SettingsWindowColors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF404040")]
        public string Фон {
            get {
                return ((string)(this["Фон"]));
            }
            set {
                this["Фон"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Заголовок {
            get {
                return ((string)(this["Заголовок"]));
            }
            set {
                this["Заголовок"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF8B8B8B")]
        public string Фон_активного_меню {
            get {
                return ((string)(this["Фон_активного_меню"]));
            }
            set {
                this["Фон_активного_меню"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF909090")]
        public string Фон_активного_подменю {
            get {
                return ((string)(this["Фон_активного_подменю"]));
            }
            set {
                this["Фон_активного_подменю"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Рамка {
            get {
                return ((string)(this["Рамка"]));
            }
            set {
                this["Рамка"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Текст {
            get {
                return ((string)(this["Текст"]));
            }
            set {
                this["Текст"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public string Активный_цветовой_канал {
            get {
                return ((string)(this["Активный_цветовой_канал"]));
            }
            set {
                this["Активный_цветовой_канал"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF404040")]
        public string Фон_кнопок {
            get {
                return ((string)(this["Фон_кнопок"]));
            }
            set {
                this["Фон_кнопок"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public string Текст_кнопок {
            get {
                return ((string)(this["Текст_кнопок"]));
            }
            set {
                this["Текст_кнопок"] = value;
            }
        }
    }
}
