//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Text.SettingsWindow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class BottomText : global::System.Configuration.ApplicationSettingsBase {
        
        private static BottomText defaultInstance = ((BottomText)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BottomText())));
        
        public static BottomText Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранить - Ctrl+S")]
        public string SaveButton {
            get {
                return ((string)(this["SaveButton"]));
            }
            set {
                this["SaveButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выход - Esc")]
        public string CancelButton {
            get {
                return ((string)(this["CancelButton"]));
            }
            set {
                this["CancelButton"] = value;
            }
        }
    }
}
