//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Text.SettingsWindow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ColorSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ColorSettings defaultInstance = ((ColorSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ColorSettings())));
        
        public static ColorSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Главное окно")]
        public string Window1 {
            get {
                return ((string)(this["Window1"]));
            }
            set {
                this["Window1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Окно настроек")]
        public string Window2 {
            get {
                return ((string)(this["Window2"]));
            }
            set {
                this["Window2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Текст")]
        public string MW1 {
            get {
                return ((string)(this["MW1"]));
            }
            set {
                this["MW1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Нажатые_клавиши")]
        public string MW2 {
            get {
                return ((string)(this["MW2"]));
            }
            set {
                this["MW2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ненажатые_клавиши")]
        public string MW3 {
            get {
                return ((string)(this["MW3"]));
            }
            set {
                this["MW3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон")]
        public string MW4 {
            get {
                return ((string)(this["MW4"]));
            }
            set {
                this["MW4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон")]
        public string SW1 {
            get {
                return ((string)(this["SW1"]));
            }
            set {
                this["SW1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заголовок")]
        public string SW2 {
            get {
                return ((string)(this["SW2"]));
            }
            set {
                this["SW2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_активного_меню")]
        public string SW3 {
            get {
                return ((string)(this["SW3"]));
            }
            set {
                this["SW3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int MainColorCount {
            get {
                return ((int)(this["MainColorCount"]));
            }
            set {
                this["MainColorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int SettingsColorCount {
            get {
                return ((int)(this["SettingsColorCount"]));
            }
            set {
                this["SettingsColorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int WindowCount {
            get {
                return ((int)(this["WindowCount"]));
            }
            set {
                this["WindowCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дополнительные окна")]
        public string Window3 {
            get {
                return ((string)(this["Window3"]));
            }
            set {
                this["Window3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон")]
        public string AW1 {
            get {
                return ((string)(this["AW1"]));
            }
            set {
                this["AW1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Текст")]
        public string AW2 {
            get {
                return ((string)(this["AW2"]));
            }
            set {
                this["AW2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int AdditionalColorCount {
            get {
                return ((int)(this["AdditionalColorCount"]));
            }
            set {
                this["AdditionalColorCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_левого_окна")]
        public string MW5 {
            get {
                return ((string)(this["MW5"]));
            }
            set {
                this["MW5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_правого_окна")]
        public string MW6 {
            get {
                return ((string)(this["MW6"]));
            }
            set {
                this["MW6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Текст_правого_окна")]
        public string MW7 {
            get {
                return ((string)(this["MW7"]));
            }
            set {
                this["MW7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Тескт_левого_окна")]
        public string MW8 {
            get {
                return ((string)(this["MW8"]));
            }
            set {
                this["MW8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_выделенного_элемента")]
        public string MW9 {
            get {
                return ((string)(this["MW9"]));
            }
            set {
                this["MW9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Граница_выделенного_элемента")]
        public string MW10 {
            get {
                return ((string)(this["MW10"]));
            }
            set {
                this["MW10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_активного_подменю")]
        public string SW4 {
            get {
                return ((string)(this["SW4"]));
            }
            set {
                this["SW4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Рамка")]
        public string SW5 {
            get {
                return ((string)(this["SW5"]));
            }
            set {
                this["SW5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заголовок")]
        public string AW3 {
            get {
                return ((string)(this["AW3"]));
            }
            set {
                this["AW3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_текста")]
        public string AW4 {
            get {
                return ((string)(this["AW4"]));
            }
            set {
                this["AW4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_кнопки")]
        public string AW5 {
            get {
                return ((string)(this["AW5"]));
            }
            set {
                this["AW5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Текст_кнопки")]
        public string AW6 {
            get {
                return ((string)(this["AW6"]));
            }
            set {
                this["AW6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Текст")]
        public string SW6 {
            get {
                return ((string)(this["SW6"]));
            }
            set {
                this["SW6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Активный_цветовой_канал")]
        public string SW7 {
            get {
                return ((string)(this["SW7"]));
            }
            set {
                this["SW7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_кнопок")]
        public string SW8 {
            get {
                return ((string)(this["SW8"]));
            }
            set {
                this["SW8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Текст_кнопок")]
        public string SW9 {
            get {
                return ((string)(this["SW9"]));
            }
            set {
                this["SW9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фон_слайдера")]
        public string MW11 {
            get {
                return ((string)(this["MW11"]));
            }
            set {
                this["MW11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ползунок_сдайдера")]
        public string MW12 {
            get {
                return ((string)(this["MW12"]));
            }
            set {
                this["MW12"] = value;
            }
        }
    }
}
