//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties.UserSettings.Text.SettingsWindow {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Fonts : global::System.Configuration.ApplicationSettingsBase {
        
        private static Fonts defaultInstance = ((Fonts)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Fonts())));
        
        public static Fonts Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Properties\\Resources\\Font\\Bankir-Retro.ttf#Bankir-Retro")]
        public string Заголовок {
            get {
                return ((string)(this["Заголовок"]));
            }
            set {
                this["Заголовок"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Properties\\Resources\\Font\\Bankir-Retro.ttf#Bankir-Retro")]
        public string Верхняя_панель {
            get {
                return ((string)(this["Верхняя_панель"]));
            }
            set {
                this["Верхняя_панель"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Properties\\Resources\\Font\\Bankir-Retro.ttf#Bankir-Retro")]
        public string Нижняя_панель {
            get {
                return ((string)(this["Нижняя_панель"]));
            }
            set {
                this["Нижняя_панель"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\Properties\\Resources\\Font\\Bankir-Retro.ttf#Bankir-Retro")]
        public string Элемент_настроек {
            get {
                return ((string)(this["Элемент_настроек"]));
            }
            set {
                this["Элемент_настроек"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Count {
            get {
                return ((int)(this["Count"]));
            }
            set {
                this["Count"] = value;
            }
        }
    }
}
