//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeMax_File_Manager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Directory, Archive, Compressed")]
        public global::System.IO.FileAttributes RightAttributes {
            get {
                return ((global::System.IO.FileAttributes)(this["RightAttributes"]));
            }
            set {
                this["RightAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Directory, Archive, Compressed")]
        public global::System.IO.FileAttributes LeftAttributes {
            get {
                return ((global::System.IO.FileAttributes)(this["LeftAttributes"]));
            }
            set {
                this["LeftAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hidden, System, Temporary")]
        public global::System.IO.FileAttributes NegRigthAttributes {
            get {
                return ((global::System.IO.FileAttributes)(this["NegRigthAttributes"]));
            }
            set {
                this["NegRigthAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hidden, System, Temporary")]
        public global::System.IO.FileAttributes NegLeftAttributes {
            get {
                return ((global::System.IO.FileAttributes)(this["NegLeftAttributes"]));
            }
            set {
                this["NegLeftAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string CurLeftFolder {
            get {
                return ((string)(this["CurLeftFolder"]));
            }
            set {
                this["CurLeftFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\")]
        public string CurRightFolder {
            get {
                return ((string)(this["CurRightFolder"]));
            }
            set {
                this["CurRightFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Настройки")]
        public string wSettingsTitle {
            get {
                return ((string)(this["wSettingsTitle"]));
            }
            set {
                this["wSettingsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FreeMax File Manager")]
        public string wMainTitle {
            get {
                return ((string)(this["wMainTitle"]));
            }
            set {
                this["wMainTitle"] = value;
            }
        }
    }
}
